# mailrelay/Dockerfile
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# create non-root
RUN addgroup -S app && adduser -S app -G app
USER app
EXPOSE 4001
CMD ["node", "server.js"]
